id: I5E0DF1E2
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:15:38.754896
last_modified: 2023-02-08 15:15:38.754996
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: sa
bases:
  BF9B:
    base_file: BF9B.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
